/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pretty_tools_dde_server_DDEServer */

#ifndef _Included_com_pretty_tools_dde_server_DDEServer
#define _Included_com_pretty_tools_dde_server_DDEServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pretty_tools_dde_server_DDEServer
 * Method:    nativeStart
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pretty_1tools_dde_server_DDEServer_nativeStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pretty_tools_dde_server_DDEServer
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pretty_1tools_dde_server_DDEServer_nativeStop
  (JNIEnv *, jobject);

/*
 * Class:     com_pretty_tools_dde_server_DDEServer
 * Method:    nativeNotifyClients
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pretty_1tools_dde_server_DDEServer_nativeNotifyClients
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
